# This plugin optionally uses bStats to collect (non-identifying) data about the usage of the plugin. This can be opted out of by setting this to false.
bstats-enabled: true

# Don't change this unless you know what you're doing
database-path: "null"

text-reactions:
  enabled: true

  # The set of reactions that will be randomly chosen from if text reactions are chosen.
  # Players can run the command "/re {reaction}" to win the game and trigger the "reward-command" (see below)
  reactions:
    - "players can type this to win!"
    - "or type this!"
    - "add your own chat reactions here"

# If enabled, this creates a random, simple math problem for players to solve. The first to run /re {correct-answer} wins!
math-reactions:
  addition:
    enabled: true
    number1-range: # Ranges are inclusive of both boundary numbers
      start: 1
      end: 999
    number2-range:
      start: 1
      end: 999

  subtraction:
    enabled: true
    number1-range:
      start: 1
      end: 999
    number2-range:
      start: 1
      end: 999

  multiplication:
    enabled: true
    number1-range:
      start: 1
      end: 20
    number2-range:
      start: 1
      end: 20

  division:
    enabled: true
    answer-range:
      start: 1
      end: 20
    divisor-range:
      start: 1
      end: 10

# How long should there be between chat games in seconds?
delay:
  # This would ensure that there is always 2 minutes between the beginning of chat games
  fixed-delay: 120

  # If you would instead like to use a random delay, set fixed-delay to -1
  random-delay-range:
    start: 0
    end: 0

# How long (in seconds) after the chat game starting should it expire if no one has gotten the answer? If you'd like to disable this, set it to 0.
timeout: 90

# The command to be run when a player correctly answers the chat task. Here, {player} is a placeholder that will be replaced with the winner's username. This example requires an economy plugin to work
reward-command: "eco give {player} 5000"

# Messages use MiniMessage
messages:
  new-game: "<#ff0000>Chat<#ffffff>Reactions » <#0064ff> Type <#ffffff>{command} <#0064ff>first to win $5,000!"
  winner-announcement: "<#ff0000>Chat<#ffffff>Reactions » {player} <#0064ff>got it right in <#ffffff>{seconds}<#0064ff>s!"
  no-reaction: "<#ff0000>There is no active chat reaction!"
  incorrect-reaction: "<#ff000>Incorrect reaction!"
  timeout: "<#ff0000>Chat<#ffffff>Reactions » <#ff0000>Nobody got it in time :("
  no-internet: "<red>ChatReactions cannot access the GitHub API! Is the server connected to the Internet?"
  new-version: "<#ff0000>Chat<#ffffff>Reactions » There is a new version of the plugin available! Version {new-version} is available, but you are still using {old-version}. Download it at: <red><b><u>https://modrinth.com/plugin/chatreactions/releases/{new-version}"
  stats: "<#ff0000>Chat<#ffffff>Reactions » Stats ({player})\n
  <#ff0000>Games Won: <white>{won}\n
  <#ff0000>Games Played: <white>{played}\n
  <#ff0000>Total Attempts: <white>{attempts}\n"
  never-played: "<red>This user has never played before, and so has no stats."
  reloaded: "<green>Config successfully reloaded!"

sounds:
  new-game-notification:
    name: BLOCK_NOTE_BLOCK_XYLOPHONE
    volume: 1.0
    pitch: 1.0
  command-failed:
    name: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 0.2
  command-succeed-generic:
    name: BLOCK_NOTE_BLOCK_PLING
    volume: 1.0
    pitch: 2.0
  self-player-won:
    name: BLOCK_NOTE_BLOCK_XYLOPHONE
    volume: 1.0
    pitch: 2.0
  other-player-won:
    name: BLOCK_NOTE_BLOCK_XYLOPHONE
    volume: 1.0
    pitch: 0.5
  timeout:
    name: BLOCK_NOTE_BLOCK_XYLOPHONE
    volume: 1.0
    pitch: 0.2

